/*
 * Michael Masenheimer CSC 345 
 * Program #1: Somewhat Simplified Solitaire Encryption Algorithm: Two–Suit Variant
 * Dr. McCann, Dr. Lynam, Jesse Chen, Moyeen Uddin, due September 18
 * 
 * Description:
 *
 * This program was written to refresh my java skills. It is a play on a classic solitaire encryption/decryption
 * algorithm using keystreams generated by a half deck of cards. In terms of data structures, only fixed arrays
 * were used since all of the input and output data doesn't necessarily need to be changed. This program
 * uses what is called a "keystream" algorithm, which involves shifting the deck of cards around to generate custom
 * values used in the encryption/decription process for each character in the input and output.
 * 
 * Operations:
 * This program uses Java version 24, and the input is taken from the terminal in the form of "encryption/decryption.java messages.txt deck.txt"
 * 
 * As far as I know, all possible placements of jokers and valid decks are handled. Few bugs with
 * file ins and valid deck checking.
 */

/*
 * Class: Decrypt.java
 * Name: Michael Masenheimer
 * Package: Project 1 (No inheritence), relies on ConvertDeck.java and keystream.java
 * 
 * Purpose: This class represents a decryption algorithm to decrypt a previous encrypted message. It relies
 * on keystream values generated by keystream.java on the input deck. In essence, this class does the calculations
 * to decrypt based on those keystream values, also handling file errors and i/o.
 * 
 * There are no public constants and no public variables (fields) declared in this class.
 * All variables are declared as local variables inside methods.
 * 
 * Decrypt also has no explicitly defined constructors
 */


import java.io.File;
import java.io.FileNotFoundException;
import java.util.HashMap;
import java.util.Scanner;

public class Decrypt {

    /*
     * Method: decrypt
     * Purpose: Decrypts an encrypted message using the Solitaire cipher and prints the decrypted text.
     * Pre-condition: 
     *   - message contains the encrypted text.
     *   - deck contains integers representing a valid deck (1-28) for keystream generation.
     * Post-condition: The deck is modified according to keystream generation steps.
     * Return value: Returns the modified deck (primary effect is printing decrypted message).
     * Parameters:
     *   - message (in): String containing the encrypted message.
     *   - deck (in/out): Integer array representing the deck; modified by keystream operations.
    */

    public static Integer[] decrypt (String message, Integer[] deck) {

        HashMap<Character, Integer> map = new HashMap<>();

        for (char c = 'A'; c <= 'Z'; c++) {
            map.put(c, c - 'A' + 1);
        }
        // Map letters to their respective number in the alphabet

        String converted = "";

        for (int i = 0; i < message.length(); i++) {
            // Clean the input message to be only letters and be uppercase
            char ch = message.charAt(i);

            if (Character.isLetter(ch)) {
            converted += Character.toUpperCase(ch);

            }
        }

       Integer[] numbered = new Integer[converted.length()];
        for (int i = 0; i < converted.length(); i++) {
            // Convert letters to numbers
            numbered[i] = map.get(converted.charAt(i));
        }

        int numIterations = (numbered.length);
        Integer[] keyStreamValues = new Integer[numIterations];
        // Generate new array for the keystream values

        Integer[] finalResultArr = new Integer[keyStreamValues.length];
        int index = 0;
        while (index < numIterations) {
            // Generate keystream values based on the current item in the deck
            keyStreamValues[index] = keystream.findKeyStream(deck);

            index += 1;
        }

        for (int i = 0; i < keyStreamValues.length; i++) {
            // Subtract keystream to decrypt numbers

            if (numbered[i] <= keyStreamValues[i]) {
                numbered[i] += 26;
            }
            int tmp = numbered[i] - keyStreamValues[i];
            
            finalResultArr[i] = tmp;
        }

        StringBuilder finalResult = new StringBuilder();
        // Return string

        for (int num : finalResultArr) {
             // Convert numbers back to letters
            if (num >= 1 && num <= 26) {
                char c = (char) ('A' + num - 1);
                finalResult.append(c);
            }
        }

        System.out.println(finalResult);

        return deck;

    }

    /*
     * Method: isValidDeck
     * Purpose: Checks whether a given deck is valid for encryption.
     * Pre-condition: The deck array is not null.
     * Post-condition: Returns true if the deck contains exactly 28 cards, with values 1–28, each exactly once.
     * Return value: boolean – true if deck is valid, false otherwise.
     * Parameters:
     *   - deck (in): Array of Integer representing a deck of cards.
    */
    private static boolean isValidDeck(Integer[] deck) {
        // Must have 28 cards
        if (deck.length != 28) {
            return false;
        }

        // All cards 1-28 exactly once
        boolean[] found = new boolean[29]; 
        // index 1-28
        for (int card : deck) {
            if (card < 1 || card > 28) return false;
            if (found[card]) return false; 
            // There is a duplicate card
            found[card] = true;
        }
        return true;
    }

    /*
     * Method: main
     * Purpose: Reads messages and a deck from files, validates the deck, and deccrypts each message.
     * Pre-condition: Files specified as command-line arguments exist and contain valid data.
     * Post-condition: Messages are encrypted and printed to output; scanners are closed.
     * Return value: None
     * Parameters:
     *   - args (in): Command-line arguments: args[0] = messages file, args[1] = deck file.
    */
    public static void main(String[] args) {

        File inputDeck = new File(args[0]);
        File inputMessages = new File(args[1]);

        // Check if files exist
        if (!inputMessages.exists()) {
            System.out.println("messages.txt does not exist.");
            return;
        }
        if (!inputDeck.exists()) {
            System.out.println("deck does not exist.");
            return;
        }

        try {
            Scanner messageScanner = new Scanner(inputMessages);
            Scanner deckScanner = new Scanner(inputDeck);

            // Read and convert deck
            if (!deckScanner.hasNextLine()) {
                System.out.println("Deck file is empty.");
                deckScanner.close();
                messageScanner.close();
                return;
            }

            String theDeck = deckScanner.nextLine();
            Integer[] convertedDeck = ConvertDeck.startConvert(theDeck);

            // Validate deck
            if (!isValidDeck(convertedDeck)) {
                System.out.println("Deck is invalid.");
                deckScanner.close();
                messageScanner.close();
                return;
            }

            // Encrypt each message line
            while (messageScanner.hasNextLine()) {
                String curr = messageScanner.nextLine();
                decrypt(curr, convertedDeck);
            }

            messageScanner.close();
            deckScanner.close();

        } catch (FileNotFoundException e) {
            System.out.println("One of the files could not be found.");

        } catch (Exception e) {
            System.out.println("An unexpected error occurred: " + e.getMessage());
        }
    }
}